# Generated by Django 3.1.2 on 2020-10-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=60)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('unit', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=60)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('joindate', models.CharField(max_length=50)),
                ('endate', models.CharField(max_length=50)),
                ('initalamount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('duration', models.DurationField()),
            ],
        ),
    ]
