# Generated by Django 3.1.2 on 2020-10-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='endate',
        ),
        migrations.AddField(
            model_name='member',
            name='expiredate',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='age',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='date',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='desc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='unit',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='initalamount',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.CharField(max_length=10),
        ),
    ]
