# Generated by Django 3.1.2 on 2020-10-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_auto_20201013_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='plan',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
